#ifndef ZCONFIG_H
#define ZCONFIG_H

enum ePlayerEnum
{
    PLAYER_BEGIN,
    COSTUME_SB_1 = 0,
    COSTUME_SB_2,
    COSTUME_SB_3,
    COSTUME_SB_4,
    COSTUME_SB_5,
    COSTUME_SB_6,
    COSTUME_SB_7,
    COSTUME_SB_A,
    COSTUME_SB_B,
    COSTUME_SB_C,
    COSTUME_SB_D,
    COSTUME_SB_X = 0xa,
    COSTUME_PAT_1,
    COSTUME_PAT_2,
    COSTUME_PAT_3,
    COSTUME_PAT_4,
    COSTUME_PAT_5,
    COSTUME_PAT_6,
    COSTUME_PAT_7,
    COSTUME_PAT_A,
    COSTUME_PAT_B,
    COSTUME_PAT_C,
    COSTUME_PAT_D,
    COSTUME_PAT_X = 0x15,
    SPONGEPAT_0,
    SPONGEPAT_1,
    SPONGEPAT_2,
    CAR_NORMAL,
    SPONGEBALL_NORMAL,
    PLAYER_COUNT
};

#endif
